### ISSUE TITLE
What is the name of the project?

### ISSUE THREAD

**Issue by ugnelis** [HacktoberfestMunich/Presentations#4]
Hey,

I am missing information about the guy who introduced State Machines described by text. Could you post here the link?

Best,
Ugnius

**Comment by ugnelis** [comment]
I have found it: Sisyphus - The simple finite state machine generator (https://github.com/TobiasPleyer/sisyphus).

**Comment by TobiasPleyer** [comment]
Correct. Thank you for your question and your interest!

Cheers
Tobias

Ugnius Malūkas <notifications@github.com> schrieb am Mo., 15. Okt. 2018
13:38:
